#!/usr/bin/env ruby
#^syntax detection

site 'http://supermarket.getchef.com/api/v1'

cookbook "apt"
cookbook "application", "~> 3.0"
cookbook 'chef-client'
cookbook "ntp"
cookbook "ruby_build"
cookbook "ssh_known_hosts"
cookbook "sudo"
cookbook "timezone"
cookbook "users"

#Bullshit. We don't even use this cookbook but it sure did introduce a
#circular dependency
cookbook "windows", "<=1.12.3"

cookbook "fuelfocus-api",
  :path => "site-cookbooks/fuelfocus-api"
  
cookbook "gpg",
  :git => "https://github.com/VendaTech/chef-cookbook-gpg.git"

cookbook "kedpm",
  :git => "https://github.com/umts/chef-kedpm"

cookbook "kedpm-transit",
  :git => "https://github.com/umts/chef-kedpm-transit"

cookbook "oit-email",
  :path => "site-cookbooks/oit-email"

cookbook "motd-tail",
  :git => "https://github.com/umts/motd-tail"

cookbook "rbenv",
  :git => 'https://github.com/fnichol/chef-rbenv', :ref => 'v0.7.2'

cookbook "python",
  :git => "https://github.com/opscode-cookbooks/python.git"

cookbook "round-three",
  :git => "https://github.com/umts/chef-round-three.git"

cookbook "jenkins",
  :git => "https://github.com/umts/chef-jenkins.git"

cookbook "rsnapshot",
  :git => "https://github.com/umts/rsnapshot.git"

cookbook "ruby-193",
  :path => "site-cookbooks/ruby-193"

cookbook "shibboleth",
  :git => "https://github.com/umts/chef-shibboleth.git"

cookbook "ssl",
  :git => "https://github.com/VendaTech/chef-cookbook-ssl.git"

cookbook "ssmtp",
  :git => "https://github.com/umts/chef-ssmtp.git"
