#!/usr/bin/env ruby
#^syntax detection

site 'http://community.opscode.com/api/v1'

cookbook "apt"
cookbook 'chef-client'
cookbook "ntp"
cookbook "sudo"
cookbook "timezone"
cookbook "users"

cookbook "kedpm",
  :git => "https://github.com/umts/chef-kedpm"

cookbook "motd-tail",
  :git => "https://github.com/umts/motd-tail"

cookbook "redmine",
  :git => "https://github.com/juanje/cookbook-redmine.git"

cookbook "redmine-custom",
  :path => "site-cookbooks/redmine-custom"

# cookbook 'apache2', '>= 1.0.0'

# cookbook 'postgresql',
#   :git => 'https://github.com/findsyou/cookbooks',
#   :ref => 'postgresql-improvements'
