# This is a rails 2.3 app, so it doesn't have access to bundler in the
# awesome way that a rails 3.0 app does, but we can still run "bundle
# install" to get these gems installed.
source "http://rubygems.org"

gem "rails", "=2.3.11"
gem "rack", "~>1.1.1"
gem "i18n", "=0.4.2"
gem "rubytree"
gem "coderay", "~>0.9.7"
gem "mysql"
